name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.3

    - name: Go mod tidy
      run: go mod tidy

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o sp-linux-amd64

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o sp-windows-amd64.exe

    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o sp-darwin-amd64

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ github.ref }}
        prerelease: false
        files: |
          sp-linux-amd64
          sp-windows-amd64.exe
          sp-darwin-amd64
